source "https://rubygems.org"

gem "jekyll", "4.2.0"  # Specify the version of Jekyll you need
gem "jekyll-theme-primer"
gem "jekyll-seo-tag"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-redirect-from"
gem "jekyll-coffeescript"
gem "jekyll-commonmark-ghpages"
gem "jekyll-github-metadata"
gem "jekyll-relative-links"
gem "jekyll-optional-front-matter"
gem "jekyll-readme-index"
gem "jekyll-default-layout"
gem "jekyll-titles-from-headings"
